package com.ahmadkharfan.androidstudiolite.feature.editor.git

import com.ahmadkharfan.androidstudiolite.domain.model.PullMode

interface GitPanelInteractionListener : GitAuthPromptActions {
    fun onSelectChange(path: String, target: com.ahmadkharfan.androidstudiolite.domain.model.GitDiffTarget)
    fun onCloseDiff()
    fun onStage(path: String)
    fun onUnstage(path: String)
    fun onStageAll()
    fun onUnstageAll()
    fun onCommitMessageChanged(message: String)
    fun onCommit()
    fun onCommitAndPush()
    fun onOpenAuthorDialog()
    fun onAuthorNameChanged(name: String)
    fun onAuthorEmailChanged(email: String)
    fun onSaveLocalAuthor()
    fun onUseAppAuthor()
    fun onDismissAuthorDialog()
    fun onPush()
    fun onFetch()
    fun onPull()
    fun onPullModeChanged(mode: PullMode)
    fun onCancelOperation()
    fun onRequestForcePush()
    fun onConfirmForcePush()
    fun onDismissForcePush()
    fun onOpenRemotes()
    fun onCloseRemotes()
    fun onAddRemote()
    fun onEditRemote(name: String)
    fun onRemoteNameChanged(name: String)
    fun onRemoteUrlChanged(url: String)
    fun onSaveRemote()
    fun onDismissRemoteEditor()
    fun onRequestRemoveRemote(name: String)
    fun onConfirmRemoveRemote()
    fun onDismissRemoveRemote()
    fun onRefresh()
    fun onStatusMessageShown()
    fun onContinueOperation()
    fun onRequestAbortOperation()
    fun onConfirmAbortOperation()
    fun onDismissAbortOperation()
    fun onRequestRestore(path: String)
    fun onConfirmRestore()
    fun onDismissRestore()
    fun onPreviewClean()
    fun onCleanIncludeIgnoredChanged(include: Boolean)
    fun onConfirmClean()
    fun onDismissClean()
    fun onOpenSubmodules()
    fun onCloseSubmodules()
    fun onInitSubmodules()
    fun onUpdateSubmodules()
    fun onOpenBootstrap()
    fun onBootstrapInitialCommitChanged(enabled: Boolean)
    fun onBootstrapMessageChanged(message: String)
    fun onConfirmBootstrap()
    fun onDismissBootstrap()
    fun onSelectAllChanges()
    fun onClearSelection()
    fun onToggleSelect(path: String)
    fun onToggleSectionSelect(paths: List<String>, select: Boolean)
    fun onStageSelected()
    fun onUnstageSelected()
    fun onRevertSelected()
}
