package com.ahmadkharfan.androidstudiolite.feature.editor

interface EditorInteractionListener {
    fun onSelectTab(id: String)
    fun onCloseTab(id: String)
    fun onToggleMenu()
    fun onSelectRailTool(tool: EditorRailTool)
    fun onCloseDrawer()
    fun onToggleFolder(id: String)
    fun onOpenFile(id: String, name: String)
    fun onRunProject()
    fun onCancelBuild()
    fun onBuildReleaseApk()
    fun onBuildReleaseBundle()
    fun onJumpToBuildProblem(problem: com.ahmadkharfan.androidstudiolite.feature.buildrun.BuildProblem)
    fun onSelectBottomTab(id: String)
    fun onToggleBottomPanel()
    fun onCloseProject()
    fun onOpenSettings()
    fun onOpenAiAgentSettings()
    fun onSave()
    fun onUndo()
    fun onRedo()
    fun onSnackbarShown()
    fun onSimulateBuildFailure()
    fun onToggleMemoryPressure()
    fun onToggleMemoryChartExpanded()
    fun onFreeUpMemory()
    fun onSimulateLspReindex()
    fun onToggleFindBar()
    fun onFindQueryChanged(query: String)
    fun onFindNext()
    fun onFindPrevious()
    fun onToggleAutocompleteDemo()
    fun onJumpToDiagnostic(diagnostic: DiagnosticUiModel)
}
